{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: Вход в систему не выполнен\nassert False\n +  where False = <bound method AuthPage.is_logged_in of <pages.auth_page.AuthPage object at 0x108149490>>()\n +    where <bound method AuthPage.is_logged_in of <pages.auth_page.AuthPage object at 0x108149490>> = <pages.auth_page.AuthPage object at 0x108149490>.is_logged_in", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"460145918d4fa64d8eba8af224ce0519\")>\n\n    def test_login(driver):\n        auth_page = AuthPage(driver)\n        auth_page.open_login_form()\n        auth_page.enter_credentials(username=\"TestYura123\", password=\"Test12345\")\n        auth_page.submit_login()\n>       assert auth_page.is_logged_in(), \"Вход в систему не выполнен\"\nE       AssertionError: Вход в систему не выполнен\nE       assert False\nE        +  where False = <bound method AuthPage.is_logged_in of <pages.auth_page.AuthPage object at 0x108149490>>()\nE        +    where <bound method AuthPage.is_logged_in of <pages.auth_page.AuthPage object at 0x108149490>> = <pages.auth_page.AuthPage object at 0x108149490>.is_logged_in\n\ntests/test_authorization_and_registration.py:36: AssertionError"}, "start": 1741821706979, "stop": 1741821707924, "uuid": "70ed738d-7691-4bea-acf3-c31d5d8564dd", "historyId": "64ed14bba4e56324e103f70040f0793d", "testCaseId": "64ed14bba4e56324e103f70040f0793d", "fullName": "tests.test_authorization_and_registration#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_and_registration"}, {"name": "host", "value": "MacBook-Pro-Natasha.local"}, {"name": "thread", "value": "18976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_and_registration"}]}